name: "Check"

permissions:
  contents: write

on:
  workflow_dispatch:
    workflow_call:
      pull_request:
        push:
          branches:
            - main

jobs:
  cargo-fmt:
    name: Cargo fmt
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt

      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy

      - name: Rustfmt Check
        run: cargo +nightly fmt --all --check

  cargo-clippy:
    name: Cargo clippy
    runs-on: ubuntu-latest
    needs: cargo-fmt

    steps:
      - name: Clippy Check
        run: cargo clippy --workspace --all-targets --all-features -- -Dwarnings 

  cargo-test:
    name: Cargo test
    runs-on: ubuntu-latest
    needs: cargo-clippy

    steps:
      - name: Cargo test
        run: cargo test --workspace --all-targets --all-features
